"""
Data schemas for the LLM Financial Summary & Insight Engine (LIG - Overdue Recovery).
Defines strongly-typed contracts for financial insights, overdue account aging, recovery risk tiers, dual-persona views, and structured engine output using Pydantic v2.
"""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class RiskTier(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class InsightCategory(str, Enum):
    OVERDUE_RECOVERY = "overdue_recovery"
    LIQUIDITY_ANALYSIS = "liquidity_analysis"
    REVENUE_HEALTH = "revenue_health"
    WORKING_CAPITAL = "working_capital"
    RISK_FLAG = "risk_flag"


class PersonaType(str, Enum):
    CLIENT = "client"
    RELATIONSHIP_MANAGER = "relationship_manager"
    DUAL = "dual"


class OverdueAccount(BaseModel):
    """Represents a specific client invoice/receivable account requiring recovery action."""
    account_id: str = Field(..., description="Unique account/invoice identifier")
    client_name: str = Field(..., description="Name of the client or counterparty")
    overdue_amount: float = Field(..., description="Overdue monetary amount")
    currency: str = Field("USD", description="Currency ISO code")
    days_overdue: int = Field(..., description="Number of days payment is past due")
    risk_tier: RiskTier = Field(RiskTier.MEDIUM, description="Calculated recovery risk tier")
    last_payment_date: Optional[str] = Field(None, description="ISO date of last recorded payment")
    recommended_action: str = Field(..., description="Deterministic or LLM-guided recovery recommendation")
    recovery_probability: float = Field(0.85, ge=0.0, le=1.0, description="Estimated probability of collection (0.0 to 1.0)")


class FinancialInsight(BaseModel):
    """Represents a structured narrative financial insight generated by local LLM / rules."""
    insight_id: str = Field(..., description="Unique insight identifier")
    category: InsightCategory = Field(..., description="Primary domain of the financial insight")
    title: str = Field(..., description="Concise title summarizing the financial insight")
    description: str = Field(..., description="Detailed narrative explanation grounded in financial data")
    impact_score: float = Field(0.5, ge=0.0, le=1.0, description="Severity or importance score between 0.0 and 1.0")
    actionable_recommendation: str = Field(..., description="Actionable step for financial management")
    supporting_metrics: Dict[str, Any] = Field(default_factory=dict, description="Key numerical ratios or figures supporting insight")


class OverdueSummaryMetrics(BaseModel):
    """High-level summary metrics for overdue receivables and collections."""
    total_receivables: float = Field(0.0, description="Total accounts receivable balance")
    total_overdue_amount: float = Field(0.0, description="Total past due amount")
    overdue_ratio: float = Field(0.0, description="Overdue amount / total receivables ratio")
    critical_overdue_count: int = Field(0, description="Number of accounts with critical (>90 days) delinquency")
    average_days_overdue: float = Field(0.0, description="Weighted average days overdue")
    expected_recovery_amount: float = Field(0.0, description="Estimated collectible value based on risk weighting")


class ClientViewSummary(BaseModel):
    """Client-facing summary view: Plain-language, reassuring, resolution-focused."""
    executive_summary: str = Field(..., description="Plain-language financial health summary for client viewing")
    account_status_headline: str = Field(..., description="Status headline e.g. 'Action Needed: Payment Plan Available'")
    settlement_options: List[str] = Field(default_factory=list, description="Self-service payment and settlement options")
    self_service_actions: List[str] = Field(default_factory=list, description="Available portal actions for client")
    reassuring_note: str = Field(..., description="Supportive closing note to maintain positive business relationship")


class RMViewSummary(BaseModel):
    """Relationship Manager (RM)-facing summary view: Tactical, risk-heavy, negotiation-focused."""
    internal_risk_assessment: str = Field(..., description="Internal tactical financial risk narrative")
    collection_urgency_tier: RiskTier = Field(RiskTier.HIGH, description="Calculated collection urgency level")
    recommended_credit_limit: float = Field(0.0, description="Recommended adjusted credit line limit")
    tactical_negotiation_playbook: List[str] = Field(default_factory=list, description="Internal debt recovery and negotiation steps")
    overdue_exposure_amount: float = Field(0.0, description="Total overdue balance exposure")
    credit_hold_recommended: bool = Field(False, description="Whether an immediate credit hold is recommended")


class FinancialSummaryRequest(BaseModel):
    """Input request contract for the financial summary & insight engine."""
    document_id: str = Field(..., description="Target document ID")
    company_name: str = Field(..., description="Target company name")
    fiscal_period: str = Field("FY24", description="Fiscal year/period")
    summary_metrics: Dict[str, Optional[float]] = Field(default_factory=dict, description="Extracted standard financial metrics")
    notes_summary_text: str = Field("", description="Cleaned combined text from Notes to Accounts")
    raw_receivables_data: List[Dict[str, Any]] = Field(default_factory=list, description="Raw receivables ledger entries if available")
    persona: PersonaType = Field(PersonaType.DUAL, description="Target view persona")


class FinancialSummaryResult(BaseModel):
    """Top-level structured JSON result output by the LIG engine."""
    document_id: str = Field(..., description="Unique document ID")
    company_name: str = Field(..., description="Reporting company name")
    fiscal_period: str = Field(..., description="Fiscal period")
    executive_summary: str = Field(..., description="Executive narrative financial summary")
    overdue_metrics: OverdueSummaryMetrics = Field(default_factory=OverdueSummaryMetrics, description="Overdue receivables summary metrics")
    overdue_accounts: List[OverdueAccount] = Field(default_factory=list, description="List of categorized overdue accounts and recovery plans")
    key_insights: List[FinancialInsight] = Field(default_factory=list, description="Categorized financial insights")
    financial_risk_flags: List[str] = Field(default_factory=list, description="List of immediate risk alerts")
    status: str = Field("SUCCESS", description="Execution status ('SUCCESS', 'FALLBACK')")
    latency_ms: float = Field(..., description="Total execution latency in milliseconds")
    model_used: str = Field("llama3.2:quantized-local", description="Model identifier used for inference")
    timestamp: str = Field(..., description="ISO 8601 execution timestamp")


class DualPersonaSummaryResult(BaseModel):
    """Top-level JSON result container delivering both Client and Relationship Manager persona views."""
    document_id: str = Field(..., description="Unique document ID")
    company_name: str = Field(..., description="Reporting company name")
    fiscal_period: str = Field(..., description="Fiscal period")
    client_view: ClientViewSummary = Field(..., description="Client-facing transparent summary and self-service options")
    rm_view: RMViewSummary = Field(..., description="RM-facing internal risk analysis and collection playbook")
    overdue_metrics: OverdueSummaryMetrics = Field(default_factory=OverdueSummaryMetrics, description="Overdue receivables metrics")
    status: str = Field("SUCCESS", description="Execution status ('SUCCESS', 'FALLBACK')")
    latency_ms: float = Field(..., description="Total execution latency in milliseconds")
    model_used: str = Field("llama3.2:quantized-local", description="Model identifier")
    timestamp: str = Field(..., description="ISO 8601 execution timestamp")
